### ISSUE TITLE
spawnSync - E2BIG error

### ISSUE THREAD

**Issue by dineshkumar02** [slammayjammay/node-pager#3]
Hi Team,

Thank you much for this library, and I have used this in my current project.
But, whenever I am trying to load some 10MB data using this approach, I am facing the above error(I needed to debug the node internal packages, to get this error message).

After going throw multiple channels, I have tried to set the `maxBuffers` for the `spawnSync` which also did not work.
Because, the argument buffers for underlying `spawn() `is exceeding, and we are getting this error.

As an alternative approach, what I did is, I sent the 10Mb file content to a '/tmp' file, and then used the same `spawnSync` command, and it's working as expected. Below is the modified version of the same implementation, using '/tmp' file, and would like to see if we can have any other implementations with named pipes or others.

```

const { join } = require('path');
const { spawnSync } = require('child_process');
const tmp = require('tmp');
const fs = require('fs');

module.exports = data => {
	return new Promise(resolve => {
		const tmpobj = tmp.fileSync();
		if (process.platform === 'win32') {
			const file = join(__dirname, '../helpers/pager.ps1');
			spawnSync('powershell', ['-File', file, string], { stdio: 'inherit', maxBuffer: 13221225472});
		} else {
			fs.writeSync(tmpobj.fd, data);
			fs.closeSync(tmpobj.fd);
			spawnSync(`cat ${tmpobj.name}|less -FRS`, [], { shell: true, stdio: 'inherit', maxBuffer: 13221225472, encoding: 'utf8'});
		}
		resolve();
	});
};
```
Please let me know your thoughts and suggestions on this.

--Dinesh Kumar

**Comment by slammayjammay** [comment]
Hey Dinesh thanks for investigating, I agree tmp files seem the best way. I'll make a new release soon, in the meantime your changes are in branch `big-strings`

**Comment by dineshkumar02** [comment]
Thank you very much @slammayjammay.

**Comment by slammayjammay** [comment]
https://github.com/slammayjammay/node-pager/releases/tag/0.3.5
